require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe']

RSpec/MultipleExpectations:
  Enabled: false
