default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: rostik
  password: rostik


development:
  <<: *default
  database: todolistAPI

test:
  <<: *default
  database: test_todolistAPI

production:
  <<: *default
  adapter: postgresql
  database: todolistAPI_prod
